ALTER TABLE takeoff_items ADD COLUMN IF NOT EXISTS multiplier NUMERIC DEFAULT 1;
ALTER TABLE takeoff_items ADD COLUMN IF NOT EXISTS height NUMERIC;
ALTER TABLE takeoff_items ADD COLUMN IF NOT EXISTS depth NUMERIC;
ALTER TABLE takeoff_items ADD COLUMN IF NOT EXISTS waste_pct NUMERIC DEFAULT 0;
