ALTER TABLE takeoff_items ADD COLUMN IF NOT EXISTS pitch TEXT;
ALTER TABLE takeoff_items ADD COLUMN IF NOT EXISTS pitch_multiplier NUMERIC DEFAULT 1.0;
ALTER TABLE takeoff_items ADD COLUMN IF NOT EXISTS waste_percent NUMERIC DEFAULT 0;
